// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwbldfqsmcaqpdwiodrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3YmxkZnFzbWNhcXBkd2lvZHJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNTkxMzgsImV4cCI6MjA2OTgzNTEzOH0.ZhdiQzMJbk1dpKY512_3DY_3GbpZIK_Tc56Rpw2nkZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});