// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwbldfqsmcaqpdwiodrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3YmxkZnFzbWNhcXBkd2lvZHJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODU3NzAsImV4cCI6MjA3MTQ2MTc3MH0.OjcY3ZkjPWG9Rf3RX80zX8k6MQh1xplVDkC1FBRyDdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});